package.path = "./?.lua;./?/init.lua;" .. package.path

local test = require("tests.test_helper")

require("tests.spec.client_profile_spec")
require("tests.spec.compatibility_spec")
require("tests.spec.command_router_spec")
require("tests.spec.persistence_spec")
require("tests.spec.libraries_spec")
require("tests.spec.name_normalizer_spec")
require("tests.spec.note_parser_spec")
require("tests.spec.reconcile_engine_spec")
require("tests.spec.conflict_queue_spec")
require("tests.spec.departures_spec")
require("tests.spec.organize_spec")
require("tests.spec.manual_decisions_spec")
require("tests.spec.roster_navigation_spec")
require("tests.spec.player_panel_spec")
require("tests.spec.chat_tags_spec")
require("tests.spec.officer_authority_spec")
require("tests.spec.sync_facts_spec")
require("tests.spec.sync_digest_spec")
require("tests.spec.sync_session_spec")
require("tests.spec.sync_simulation_spec")
require("tests.spec.entry_points_spec")
require("tests.spec.fellowship_store_spec")
require("tests.spec.roster_view_model_spec")
require("tests.spec.guild_roster_adapter_spec")
require("tests.spec.comm_adapter_spec")
require("tests.spec.scan_scheduler_spec")
require("tests.spec.scan_performance_spec")
require("tests.spec.roster_controller_spec")
require("tests.spec.lifecycle_spec")
require("tests.spec.bootstrap_spec")

if not test.run() then
    os.exit(1)
end
